init
SirJohanot/ball pull request #1
Opened 2021-11-26 13:00 UTC by SirJohanot

2021-11-27 07:57 UTC, FilippStankevichTR requested changes

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/dao/DataReader.java
> +            while ((temp=bufferedReader.readLine())!=null)
String line= bufferedReader.readLine(); 
 while ((temp=bufferedReader.readLine())!=null) {
     result.add(line);
     line= bufferedReader.readLine(); 
}

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/dao/DataReader.java
> +            throw new DataException("Could not find file by that path");
throw new DataException("Could not find file by that path", e);

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/dao/DataException.java
> +    public DataException(String message){
public DataException(String message, e)

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/entity/Ball.java
> +        if (this == o) return true;
if (this == o) {
 return true;
}

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/entity/Ball.java
> +    public Ball(double radius, Point center) {
Point center, double radius

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/logic/BallCalculator.java
> +        if (!isCrossingTheCoordinatePlane(ball, plane)) return 0;
if (!isCrossingTheCoordinatePlane(ball, plane)) {
   return 0;
}

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/logic/BallCreator.java
> +
private final static String DELEMITER = " ";

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/logic/BallValidator.java
> +    private static final String BALL_LINE_REGEX="\\d+\\.\\d+ (-)?\\d+\\.\\d+ (-)?\\d+\\.\\d+ (-)?\\d+\\.\\d+";
\\d+\\.\\d+ (-)?{4}

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/entity/Point.java
> +    private double xCoordinate;
final

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/logic/Director.java
> +    private DataReader reader;
final

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/logic/Director.java
> +            if (validator.isValidBallLine(line)){
isValidLine

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/main/java/com/epam/ball/logic/Director.java
> +                balls.add(creator.create(line));
Ball ball = creator.create(line);

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/test/java/com/epam/ball/logic/BallCalculatorTest.java
> +    public void testShouldCalculateSurfaceAreaWhenBallIsValid() {
testCalculateSurfaceAreaShouldCalculateWhenBallIValid

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/test/java/com/epam/ball/logic/BallCreatorTest.java
> +
private static fina String VALID_LINE = "4.0 1.0 2.0 3.0";

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/test/java/com/epam/ball/logic/BallCreatorTest.java
> +
private final  BallCreator creator=new BallCreator();

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/test/java/com/epam/ball/logic/DataReaderTest.java
> +        Assert.assertEquals(strings, result);
Arrays.asList("1.0 2.0 3.0 4.0");

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/test/java/com/epam/ball/logic/DataReaderTest.java
> +        Assert.assertEquals(strings, result);
List<String> expectedLines = Arrays.asList("1.0 2.0 3.0 4.0", "line", "12345");
  Assert.assertEquals(expectedLines  , result);

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/test/java/com/epam/ball/logic/DirectorTest.java
> +        DataReader reader= Mockito.mock(DataReader.class);
DataReader reader= Mockito.mock(DataReader.class); 
Mockito.when(reader.read(path)).thenReturn(lines);

2021-11-27 07:57 UTC, FilippStankevichTR commented on src/test/java/com/epam/ball/logic/DirectorTest.java
> +
private final static String TEST_PATH = "path";

2021-12-25 11:49 UTC, ingenmech requested changes

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/dao/DataReader.java
> +            throw dataException;
in one line throw new DataException(e.getMessage(), e);
no need log if you throw new exception

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/entity/Ball.java
> +        center = new Point();
private Point center = new Point() ; init in one line

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/entity/Point.java
> +        xCoordinate = yCoordinate = zCoordinate = 0;
no need to init, They have been inited by default

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/logic/BallCalculator.java
> +        double ratio = lesserHemisphereVolume / (calculateVolume(ball) - lesserHemisphereVolume);
you can write in one line : return lesserHemisphereVolume / (calculateVolume(ball) - lesserHemisphereVolume);

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/logic/BallCalculator.java
> +        boolean isCrossing = Math.abs(coordinate) <= radius;
in one line no need variable, for all code

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/logic/BallCreator.java
> +    public BallCreator() {
no need empty constructors for all codes

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/logic/Director.java
> +        } catch (DataException e) {
why block catch is empty

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/repository/CenterXCoordinateBallComparator.java
> +    public int compare(BallObservable o1, BallObservable o2) {
naming firstObserver, secondObserver

2021-12-25 11:49 UTC, ingenmech commented on src/main/java/com/epam/ball/repository/CenterXCoordinateBallComparator.java
> +        double xCoordinate2 = center2.getXCoordinate();
naming

2022-11-05 11:12 UTC, merged